# Generated by Django 5.2 on 2025-06-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooladmin',
            options={},
        ),
        migrations.AlterModelManagers(
            name='schooladmin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='SchoolAdminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='schools.schooladmin')),
            ],
        ),
    ]
