# Generated by Django 5.2 on 2025-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_schooladmin_options_alter_schooladmin_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooladmintoken',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='schooladmintoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='schooladmintoken',
            name='key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
