# Generated by Django 5.2 on 2025-06-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_rename_admin_schooladmintoken_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooladmintoken',
            options={'verbose_name': 'School Admin Token', 'verbose_name_plural': 'School Admin Tokens'},
        ),
        migrations.AlterField(
            model_name='schooladmintoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='schools.schooladmin', verbose_name='School Admin'),
        ),
    ]
