# Generated by Django 5.2 on 2025-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_schooladmin_options_alter_schooladmin_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmin',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('REGISTRAR', 'Registrar'), ('FINANCIAL', 'Financial Officer'), ('ACCOUNTANT', 'Accountant'), ('VICE_PRINCIPAL', 'Vice Principal'), ('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('SECURITY', 'Security')], default='ADMIN', max_length=20),
        ),
    ]
