# Generated by Django 5.2.2 on 2025-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='super_admin_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='super_admin_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
