# Generated by Django 5.2 on 2025-06-08 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='EduCloud', max_length=100)),
                ('system_email', models.EmailField(blank=True, max_length=255)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_encryption', models.CharField(choices=[('TLS', 'TLS'), ('SSL', 'SSL'), ('NONE', 'None')], default='TLS', max_length=4)),
                ('default_language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish')], default='English', max_length=20)),
                ('default_timezone', models.CharField(choices=[('UTC', 'UTC'), ('GMT', 'GMT'), ('EST', 'EST'), ('PST', 'PST')], default='UTC', max_length=20)),
                ('default_date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY')], default='YYYY-MM-DD', max_length=20)),
                ('default_time_format', models.CharField(choices=[('12', '12-hour'), ('24', '24-hour')], default='24', max_length=2)),
                ('default_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=3)),
                ('min_password_length', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(8)])),
                ('password_requires_special', models.BooleanField(default=True)),
                ('password_requires_number', models.BooleanField(default=True)),
                ('password_requires_uppercase', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=60, help_text='Session timeout in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_login_attempts', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('lockout_duration', models.IntegerField(default=30, help_text='Account lockout duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('email_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('maintenance_notifications', models.BooleanField(default=True)),
                ('security_notifications', models.BooleanField(default=True)),
                ('google_api_key', models.CharField(blank=True, max_length=255)),
                ('enable_google_login', models.BooleanField(default=False)),
                ('enable_microsoft_login', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
