# Generated by Django 5.2 on 2025-06-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_schooladmin_options_alter_schooladmin_managers_and_more'),
        ('schools_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('core_values', models.JSONField(default=list)),
                ('accreditation_info', models.TextField(blank=True)),
                ('accreditation_status', models.CharField(blank=True, max_length=50)),
                ('accreditation_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_buildings', models.IntegerField(blank=True, null=True)),
                ('num_classrooms', models.IntegerField(blank=True, null=True)),
                ('num_labs', models.IntegerField(blank=True, null=True)),
                ('num_libraries', models.IntegerField(blank=True, null=True)),
                ('sports_facilities', models.JSONField(default=list)),
                ('num_teaching_staff', models.IntegerField(blank=True, null=True)),
                ('num_non_teaching_staff', models.IntegerField(blank=True, null=True)),
                ('student_teacher_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('programs_offered', models.JSONField(default=list)),
                ('languages_taught', models.JSONField(default=list)),
                ('extra_curricular', models.JSONField(default=list)),
                ('has_transportation', models.BooleanField(default=False)),
                ('num_buses', models.IntegerField(blank=True, null=True)),
                ('transport_routes', models.JSONField(default=list)),
                ('has_medical_room', models.BooleanField(default=False)),
                ('num_medical_staff', models.IntegerField(blank=True, null=True)),
                ('medical_facilities', models.JSONField(default=list)),
                ('canteen_capacity', models.IntegerField(blank=True, null=True)),
                ('has_smart_classes', models.BooleanField(default=False)),
                ('has_solar_power', models.BooleanField(default=False)),
                ('has_generator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Details',
                'verbose_name_plural': 'School Details',
            },
        ),
    ]
