# Generated by Django 5.2 on 2025-06-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_adding_users', '0001_initial'),
        ('schools', '0006_alter_schooladmin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_users', to='schools.school'),
        ),
    ]
