# Generated by Django 5.2 on 2025-06-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_adding_users', '0003_schoolusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolusertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_user_token', to='school_adding_users.schooluser', verbose_name='School User'),
        ),
    ]
